/*!
 * <tggr-logo> · the TGGR Lab logo as a web component. No dependencies, no fonts to load.
 *
 *   <script src="tggr-logo.js"></script>
 *   <tggr-logo></tggr-logo>                         the ring turns (the chosen default)
 *   <tggr-logo motion="drawn"></tggr-logo>          drawn on once, then the ring turns
 *   <tggr-logo ring="none" style="width:64px">      the lockup alone, for a header
 *
 * Attributes
 *   motion   turn (default) | rungs | drawn | pointer | unzip | scroll | still
 *   ring     text (default) | double | band | none
 *   theme    auto (default) | light | dark
 *            auto follows <html data-theme="light|dark">, then <html class="dark">,
 *            then the system setting
 *   period   seconds per revolution of the ring, default 80
 *   label    accessible name, default "TGGR Lab"
 *   assets   folder holding the PNG layers, default ./assets/ beside this script
 *
 * Size it with CSS width; the height follows. Default 320px.
 * Colours can be overridden with --tggr-ink, --tggr-ink-2, --tggr-ink-dark, --tggr-ink-2-dark.
 * Method: el.replay() restarts the "drawn" sequence.
 * Everything stops under prefers-reduced-motion, and animation pauses while off screen.
 *
 * Generated by build.py from src/tggr-logo.src.js. Edit the source, then rebuild.
 */
(function () {
  'use strict';
  if (customElements.get('tggr-logo')) return;

  // ring text as outlines: Cormorant Garamond 500, glyph positions measured in Chromium
  var RING = __RING__;
  var EMBED = __EMBED__;
  var FILES = { ink: 'lock-ink.png', inkDark: 'lock-ink-dark.png', teal: 'lock-teal.png', orange: 'lock-orange.png', band: 'band.png' };
  var script = document.currentScript;
  var BASE = (window.TGGR_LOGO_ASSETS) || (script && script.src ? new URL('assets/', script.src).href : 'assets/');

  var CSS = [
    ':host { display: inline-block; position: relative; width: 320px; aspect-ratio: 1; vertical-align: middle; contain: layout;',
    '  --c-ink: var(--tggr-ink, #15302e); --c-ink-2: var(--tggr-ink-2, #5a6b68); --lt: 1; --dk: 0; --band-b: 1;',
    '  --glow: rgba(43, 181, 188, .5); --glow-a: .3; --period: 80s; }',
    ':host([data-mode="dark"]) { --c-ink: var(--tggr-ink-dark, #ece6d6); --c-ink-2: var(--tggr-ink-2-dark, #a9b3ae); --lt: 0; --dk: 1; --band-b: 1.55;',
    '  --glow: rgba(79, 192, 198, .8); --glow-a: .9; }',
    ':host([hidden]) { display: none; }',
    ':host([ring="none"]) { width: 120px; aspect-ratio: 600 / 962; }',
    '.stage { position: absolute; inset: 0; }',
    '.ring, .band { position: absolute; inset: 0; width: 100%; height: 100%; overflow: visible; }',
    '.ring { fill: var(--c-ink); }',
    '.ring.inner { fill: var(--c-ink-2); }',
    '.band { filter: brightness(var(--band-b)); }',
    /* the lockup: 44.4% of the ring's diameter, its centre 1.5% above the ring's, as in the supplied ring file */
    '.lock { position: absolute; left: 50%; top: 50%; width: 44.4%; aspect-ratio: 600 / 962; transform: translate(-50%, -51.5%); }',
    '.r-double .lock { width: 38%; }',
    '.r-band .lock { width: 43%; transform: translate(-50%, -50%); }',
    '.r-none .lock { left: 0; top: 0; width: 100%; height: 100%; transform: none; }',
    '.lock img { position: absolute; inset: 0; width: 100%; height: 100%; display: block; -webkit-user-drag: none; user-select: none; }',
    '.lock .lt { opacity: var(--lt); } .lock .dk { opacity: var(--dk); }',
    '@keyframes turn { to { transform: rotate(360deg); } }',
    '@keyframes appear { to { opacity: 1; } }',
    '@keyframes sweep { from { -webkit-mask-position: 0 0; mask-position: 0 0; } to { -webkit-mask-position: 0 100%; mask-position: 0 100%; } }',
    '@keyframes reveal { to { -webkit-mask-position: 0 0; mask-position: 0 0; } }',
    '@keyframes breathe { 50% { transform: translate(-50%, -51.5%) scale(1.02); } }',
    '@keyframes breathe-none { 50% { transform: scale(1.02); } }',
    '.spin { animation: turn var(--period) linear infinite; }',
    '.spin.inner { animation-duration: calc(var(--period) * .75); animation-direction: reverse; }',

    /* turn: pauses under the pointer */
    '.m-turn:hover .spin { animation-play-state: paused; }',
    /* rungs: the base pairs brighten in a wave down the helix */
    '.sweep { -webkit-mask-image: linear-gradient(to bottom, rgba(0,0,0,.3) 0 30%, #000 45% 55%, rgba(0,0,0,.3) 70% 100%); mask-image: linear-gradient(to bottom, rgba(0,0,0,.3) 0 30%, #000 45% 55%, rgba(0,0,0,.3) 70% 100%);',
    '  -webkit-mask-size: 100% 300%; mask-size: 100% 300%; animation: sweep 3.2s linear infinite; }',
    '.glow { filter: drop-shadow(0 0 4px var(--glow)) drop-shadow(0 0 9px var(--glow)); opacity: var(--glow-a); }',
    /* drawn: ink, then stripes, then rungs, then the ring fades in and turns */
    '.m-drawn .lock img { -webkit-mask-image: linear-gradient(to bottom, #000 50%, transparent 50%); mask-image: linear-gradient(to bottom, #000 50%, transparent 50%);',
    '  -webkit-mask-size: 100% 200%; mask-size: 100% 200%; -webkit-mask-position: 0 100%; mask-position: 0 100%; }',
    '.m-drawn .ring, .m-drawn .band { opacity: 0; animation: none; }',
    '.m-drawn.go .ink { animation: reveal 1.6s ease-out forwards; }',
    '.m-drawn.go .orange { animation: reveal 1.2s ease-out 1s forwards; }',
    '.m-drawn.go .teal { animation: reveal 1.2s ease-out 1.7s forwards; }',
    '.m-drawn.go .ring, .m-drawn.go .band { animation: appear 1.2s ease-out 2.6s forwards, turn var(--period) linear 2.6s infinite; }',
    '.m-drawn.go .ring.inner { animation: appear 1.2s ease-out 2.6s forwards, turn calc(var(--period) * .75) linear 2.6s infinite reverse; }',
    /* pointer: layers shift at different depths, the lockup breathes */
    '.m-pointer .lock { animation: breathe 5s ease-in-out infinite; }',
    '.m-pointer.r-none .lock { animation-name: breathe-none; }',
    '.m-pointer .lock img { transition: transform .25s ease-out; will-change: transform; }',
    '.m-pointer .ring, .m-pointer .band { transition: transform .4s ease-out; }',
    /* unzip: rungs out one way, stripes the other, ink fades back */
    '.m-unzip .lock img { transition: transform .7s cubic-bezier(.2, .8, .2, 1), opacity .7s; }',
    ':host(:hover) .m-unzip .teal { transform: translate(-9%, 1.5%); }',
    ':host(:hover) .m-unzip .orange { transform: translate(5%, -1%); }',
    ':host(:hover) .m-unzip .ink.lt { opacity: calc(var(--lt) * .5); }',
    ':host(:hover) .m-unzip .ink.dk { opacity: calc(var(--dk) * .5); }',
    /* scroll: the ring is driven by the page */
    '.m-scroll .ring, .m-scroll .band { will-change: transform; }',

    ':host([data-off]) .stage * { animation-play-state: paused !important; }',
    '@media (prefers-reduced-motion: reduce) {',
    '  .stage * { animation: none !important; transition: none !important; }',
    '  .m-drawn .lock img { -webkit-mask-image: none; mask-image: none; }',
    '  .m-drawn .ring, .m-drawn .band { opacity: 1; }',
    '  .sweep { -webkit-mask-image: none; mask-image: none; } .glow { display: none; }',
    '}'
  ].join('\n');

  function src(key, base) { return EMBED ? EMBED[key] : base + FILES[key]; }
  function ringSvg(d, cls, sep) {
    return '<svg class="ring spin ' + cls + '" viewBox="0 0 400 400" aria-hidden="true"><path d="' + d + '"/>' + sep + '</svg>';
  }

  // one watcher for every instance: <html data-theme>, <html class="dark">, the system setting
  var live = new Set();
  var mq = matchMedia('(prefers-color-scheme: dark)');
  var rm = matchMedia('(prefers-reduced-motion: reduce)');
  function pageDark() {
    var h = document.documentElement, t = h.getAttribute('data-theme');
    if (t === 'dark' || t === 'light') return t === 'dark';
    if (h.classList.contains('dark')) return true;
    if (h.classList.contains('light')) return false;
    return mq.matches;
  }
  function refreshAll() { live.forEach(function (el) { el._mode(); }); }
  var watching = false;
  function watch() {
    if (watching) return; watching = true;
    new MutationObserver(refreshAll).observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme', 'class'] });
    if (mq.addEventListener) mq.addEventListener('change', refreshAll); else mq.addListener(refreshAll);
    addEventListener('scroll', function () {
      if (scrollQueued) return; scrollQueued = true;
      requestAnimationFrame(function () { scrollQueued = false; live.forEach(function (el) { el._scroll(); }); });
    }, { passive: true });
  }
  var scrollQueued = false;

  class TggrLogo extends HTMLElement {
    static get observedAttributes() { return ['motion', 'ring', 'theme', 'period', 'label', 'assets']; }
    constructor() {
      super();
      this.attachShadow({ mode: 'open' });
      this._onMove = this._onMove.bind(this);
      this._onLeave = this._onLeave.bind(this);
    }
    connectedCallback() {
      live.add(this); watch();
      this.setAttribute('role', 'img');
      this._render();
      this._io = new IntersectionObserver(function (es) {
        var e = es[es.length - 1], el = e.target;
        if (e.isIntersecting) { el.removeAttribute('data-off'); if (!el._played) { el._played = true; el.replay(); } }
        else el.setAttribute('data-off', '');
      });
      this._io.observe(this);
      this.addEventListener('pointermove', this._onMove);
      this.addEventListener('pointerleave', this._onLeave);
    }
    disconnectedCallback() {
      live.delete(this);
      if (this._io) this._io.disconnect();
      this.removeEventListener('pointermove', this._onMove);
      this.removeEventListener('pointerleave', this._onLeave);
    }
    attributeChangedCallback() { if (this.isConnected) this._render(); }

    get motion() { var m = this.getAttribute('motion'); return /^(turn|rungs|drawn|pointer|unzip|scroll|still)$/.test(m) ? m : 'turn'; }
    get ring() { var r = this.getAttribute('ring'); return /^(text|double|band|none)$/.test(r) ? r : 'text'; }

    _render() {
      var m = this.motion, r = this.ring;
      var base = this.getAttribute('assets') || BASE; if (base && !/\/$/.test(base)) base += '/';
      var period = parseFloat(this.getAttribute('period'));
      this.setAttribute('aria-label', this.getAttribute('label') || 'TGGR Lab');

      var ring = '';
      if (r === 'text') ring = ringSvg(RING.single, '', '<circle cx="20" cy="200" r="2.4"/>');
      else if (r === 'double') ring = ringSvg(RING.outer, 'outer', '<circle cx="14" cy="200" r="2"/>') + ringSvg(RING.inner, 'inner', '<circle cx="48" cy="200" r="1.6"/>');
      else if (r === 'band') ring = '<img class="band spin" src="' + src('band', base) + '" alt="" aria-hidden="true">';

      var teal = '<img class="teal" src="' + src('teal', base) + '" alt="">';
      if (m === 'rungs') teal = '<img class="teal sweep glow" src="' + src('teal', base) + '" alt="">' + teal.replace('class="teal"', 'class="teal sweep"');
      var lock = '<div class="lock" aria-hidden="true">' +
        '<img class="ink lt" src="' + src('ink', base) + '" alt="">' +
        '<img class="ink dk" src="' + src('inkDark', base) + '" alt="">' +
        '<img class="orange" src="' + src('orange', base) + '" alt="">' + teal + '</div>';

      // with no moving ring, "turn" has nothing to turn; the scroll and still motions stop the CSS spin
      var still = m === 'still' || m === 'scroll' || m === 'pointer';
      this.shadowRoot.innerHTML = '<style>' + CSS + '</style><div class="stage m-' + m + ' r-' + r + '" part="stage">' + ring + lock + '</div>';
      if (still) this.shadowRoot.querySelectorAll('.spin').forEach(function (n) { n.classList.remove('spin'); });
      this._stage = this.shadowRoot.querySelector('.stage');
      if (period > 0) this._stage.style.setProperty('--period', period + 's');
      this._mode();
      if (m === 'drawn' && this._played) this.replay();
      this._scroll();
    }
    _mode() {
      var t = this.getAttribute('theme'), dark = t === 'dark' ? true : t === 'light' ? false : pageDark();
      if (dark) this.setAttribute('data-mode', 'dark'); else this.removeAttribute('data-mode');
    }
    _scroll() {
      if (this.motion !== 'scroll' || rm.matches) return;
      var a = 'rotate(' + (window.scrollY / 5) + 'deg)';
      this.shadowRoot.querySelectorAll('.ring, .band').forEach(function (n) {
        n.style.transform = n.classList.contains('inner') ? 'rotate(' + (-window.scrollY / 4) + 'deg)' : a;
      });
    }
    _onMove(e) {
      if (this.motion !== 'pointer' || rm.matches) return;
      var b = this.getBoundingClientRect(), x = (e.clientX - b.left) / b.width - .5, y = (e.clientY - b.top) / b.height - .5;
      var s = b.width / 320, root = this.shadowRoot;
      function set(sel, dx, dy) { root.querySelectorAll(sel).forEach(function (n) { n.style.transform = 'translate(' + (x * dx * s) + 'px,' + (y * dy * s) + 'px)'; }); }
      set('.ink', 4, 4); set('.orange', 10, 8); set('.teal', 18, 14);
      root.querySelectorAll('.ring, .band').forEach(function (n) { n.style.transform = 'rotate(' + (x * 10) + 'deg)'; });
    }
    _onLeave() {
      if (this.motion !== 'pointer') return;
      this.shadowRoot.querySelectorAll('.lock img, .ring, .band').forEach(function (n) { n.style.transform = ''; });
    }
    replay() {
      var s = this._stage; if (!s || this.motion !== 'drawn') return;
      s.classList.remove('go'); void s.offsetWidth; s.classList.add('go');
    }
  }
  customElements.define('tggr-logo', TggrLogo);
})();
