/**
 * reference.js - the static cheat-sheet content: tables and lists that
 * app.js renders. Edit text here; nothing else needs to change.
 */

export const MODELS = {
    head: ['Outcome', 'Model', 'Link / scale', 'The coefficient means', 'R', 'Python', 'Watch for'],
    rows: [
        ['Continuous', 'Linear regression', 'identity', 'change in y per unit x', 'lm()', 'smf.ols()', 'non-constant variance (robust SEs), non-linearity (splines), influential points'],
        ['Continuous, skewed, positive', 'Linear on log(y), or gamma GLM', 'log', '% change in y per unit x: 100·(e^β − 1)', 'lm(log(y) ~ .), glm(family = Gamma(link = "log"))', 'smf.ols("np.log(y) ~ ..."), smf.glm(family=Gamma())', 'zeros cannot be logged; back-transformed means are geometric means'],
        ['Continuous, repeated / clustered', 'Linear mixed model', 'identity', 'change in y per unit x, within and between clusters', 'lme4::lmer(), nlme::lme()', 'smf.mixedlm()', 'random-effect structure must match the design; ICC tells you how much clustering matters'],
        ['Binary', 'Logistic regression', 'logit', 'log odds ratio; e^β = OR', 'glm(family = binomial)', 'smf.logit()', 'needs ≳ 10 events per predictor; OR ≠ RR when the outcome is common; separation'],
        ['Binary, common outcome', 'Log-binomial or modified Poisson', 'log', 'log risk ratio; e^β = RR', 'glm(family = poisson) + sandwich SEs, or logbin', 'smf.glm(family=Poisson(), cov_type="HC0")', 'log-binomial often fails to converge; Poisson with robust SEs is the usual fix'],
        ['Binary, repeated / clustered', 'GLMM (logistic) or GEE', 'logit', 'conditional OR (GLMM) or population-averaged OR (GEE)', 'lme4::glmer(), geepack::geeglm()', 'smf.gee()', 'the two ORs differ; say which one you report'],
        ['Ordinal', 'Proportional-odds logistic', 'cumulative logit', 'common OR of being in a higher category', 'MASS::polr(), ordinal::clm()', 'OrderedModel()', 'test proportional odds; if it fails, partial proportional odds or multinomial'],
        ['Nominal, 3+ levels', 'Multinomial logistic', 'logit vs reference', 'relative risk ratio vs the reference category', 'nnet::multinom()', 'smf.mnlogit()', 'needs many events per category; IIA assumption'],
        ['Count', 'Poisson regression', 'log', 'log rate ratio; e^β = IRR', 'glm(family = poisson)', 'smf.poisson()', 'overdispersion is the rule, not the exception: check it'],
        ['Count, overdispersed', 'Negative binomial', 'log', 'log rate ratio; e^β = IRR', 'MASS::glm.nb(), glmmTMB', 'smf.negativebinomial()', 'use an offset for exposure; excess zeros → zero-inflated / hurdle'],
        ['Count per exposure (rate)', 'Poisson / NB with offset', 'log', 'rate ratio per unit x', 'glm(y ~ x + offset(log(time)))', 'offset=np.log(time)', 'the offset coefficient is fixed at 1, not estimated'],
        ['Proportion in (0, 1)', 'Beta regression', 'logit', 'OR-like change in the mean proportion', 'betareg::betareg()', 'smf.glm(family=Binomial()) with weights, or BetaModel', 'exact 0s and 1s need a transform or a zero/one-inflated model'],
        ['Time to event', 'Cox proportional hazards', 'log hazard', 'log hazard ratio; e^β = HR', 'survival::coxph()', 'lifelines CoxPHFitter', 'proportional hazards (Schoenfeld); informative censoring; immortal time'],
        ['Time to event, parametric', 'Weibull / AFT', 'log time', 'time ratio: e^β multiplies survival time', 'survival::survreg()', 'lifelines WeibullAFTFitter', 'distribution choice matters for extrapolation'],
        ['Time to event with competing risks', 'Fine–Gray, cause-specific Cox', 'subdistribution hazard', 'effect on cumulative incidence of this event', 'cmprsk::crr(), tidycmprsk', 'lifelines (cause-specific)', 'KM overestimates incidence when competing events exist'],
        ['Any, with heavy-tailed noise', 'Quantile (median) regression', 'identity', 'change in the median (or any quantile) per unit x', 'quantreg::rq()', 'smf.quantreg()', 'slower, wider intervals; great for skewed outcomes without transforming'],
        ['Gene counts (RNA-seq)', 'DESeq2 / edgeR / limma-voom', 'log₂', 'log₂ fold change per condition, shrunk', 'DESeq2::DESeq()', 'pydeseq2', 'put the batch in the design, never “correct” counts first; biological replicates, not technical'],
    ],
};

export const BENCHMARKS = {
    head: ['Measure', 'Small', 'Medium', 'Large', 'Used for'],
    rows: [
        ['Cohen’s d / Hedges’ g', '0.2', '0.5', '0.8', 'difference in means, in SD units'],
        ['Correlation r', '0.1', '0.3', '0.5', 'linear association'],
        ['Odds ratio (rare outcome)', '1.5', '2.5', '4', 'from d via Chinn’s conversion: 1.44, 2.5, 4.3'],
        ['η² / partial η²', '0.01', '0.06', '0.14', 'ANOVA: share of variance'],
        ['Cohen’s f', '0.1', '0.25', '0.4', 'ANOVA, power analysis'],
        ['Cohen’s w / Cramér’s V (df = 1)', '0.1', '0.3', '0.5', 'chi-square'],
        ['Cohen’s h', '0.2', '0.5', '0.8', 'difference between two proportions (arcsine)'],
        ['Probability of superiority', '0.56', '0.64', '0.71', 'Mann–Whitney; the AUC'],
        ['ICC / kappa', '< 0.5 poor', '0.5 to 0.75 moderate', '> 0.9 excellent', 'reliability (Koo & Li 2016); kappa: 0.41 to 0.6 moderate, 0.61 to 0.8 substantial'],
    ],
    note: 'Cohen called these “t-shirt sizes” and warned against them. What counts as large depends on the field: an r of 0.1 is big in genetics and tiny in psychometrics. Compare to the effects your field already knows about.',
};

export const PHRASES = [
    { term: 'p = 0.03', yes: 'If the null hypothesis were true (and the model right), data at least this far from it would show up 3% of the time.', no: 'There is a 3% chance the null is true. The result has a 97% chance of replicating. The effect is important.' },
    { term: 'p = 0.30', yes: 'The data are compatible with no effect, and with effects of the size the CI spans. The study did not detect one.', no: 'There is no effect. The groups are the same. “Trend towards significance.”' },
    { term: '95% CI 1.2 to 3.4', yes: 'The range of values compatible with the data at this level; in the long run, 95% of intervals built this way contain the true value.', no: 'There is a 95% probability the true value is in this interval (that needs a Bayesian credible interval).' },
    { term: 'OR = 2.5', yes: 'The odds are 2.5 times higher. If the outcome is rare, the risk is roughly 2.5 times higher too.', no: '“2.5 times more likely” when the outcome is common (then the risk ratio is smaller; see the converter).' },
    { term: 'HR = 0.6', yes: 'At any moment, the treated group’s event rate is 60% of the control group’s.', no: '“40% of patients were saved.” “Survival is 40% longer.” (Under an exponential model it is 1/0.6 = 1.67× longer.)' },
    { term: 'r = 0.3', yes: 'A modest linear association; 9% of the variance is shared.', no: 'x causes y. A 30% effect.' },
    { term: 'Power = 80%', yes: 'If the true effect were exactly the assumed size, 80% of such studies would reach p < 0.05.', no: 'Post hoc: “our power to detect the effect we found was 45%” is just the p-value restated.' },
    { term: 'Not significant', yes: 'Not enough evidence in this sample to rule out no effect.', no: 'Evidence of no effect. For that, show the CI excludes anything that matters (equivalence test).' },
    { term: 'Significant', yes: 'The data would be unusual under the null.', no: 'Important, large, real, or causal.' },
    { term: 'log₂FC = 1.5', yes: 'The gene is expressed 2^1.5 ≈ 2.8 times as much.', no: '1.5 times as much. 150% more.' },
    { term: 'FDR < 0.05', yes: 'Among the genes called significant, about 5% are expected to be false positives.', no: 'Each gene has a 5% chance of being a false positive.' },
];

export const PITFALLS = [
    ['Pseudoreplication', 'Twenty cells from two mice is n = 2, not n = 20. The unit of analysis is the unit that was randomized or independently sampled. Use a mixed model or average within the unit.'],
    ['Odds ratio read as risk ratio', 'With a 40% baseline, an OR of 3 is an RR of 1.7. ORs exaggerate when the outcome is common. Report risks and their difference.'],
    ['Dichotomizing a continuous variable', 'Splitting at the median throws away about a third of the information and invents a threshold that does not exist. Keep it continuous; use splines if it curves.'],
    ['Comparing p-values instead of effects', '“Significant in A, not in B” does not mean A and B differ. Test the interaction (the difference of differences).'],
    ['Multiple comparisons without saying so', 'Twenty tests at α = 0.05 give one false positive on average. Pre-specify, adjust (Holm for a few, BH for a screen), or call it exploratory.'],
    ['Post-hoc power', 'Power computed from the observed effect is a function of the p-value and adds nothing. Plan power before; after, show the CI.'],
    ['Absence of evidence', 'p = 0.4 with a CI from −50% to +80% is not “no effect”. It is “we cannot tell”. Equivalence needs a CI inside a pre-set margin.'],
    ['Table 2 fallacy', 'In an adjusted model only the exposure’s coefficient has the causal interpretation you adjusted for. The covariates’ coefficients are adjusted for different things.'],
    ['Collider bias / selection', 'Conditioning on a consequence of both exposure and outcome (hospitalization, study enrolment) creates associations from nothing.'],
    ['Immortal time bias', 'Patients had to survive long enough to receive the treatment. Count that time as unexposed (time-varying exposure), or landmark.'],
    ['Regression to the mean', 'Select the extreme values, measure again, they are less extreme. A control group, not a before/after, tells you what the treatment did.'],
    ['Simpson’s paradox', 'A trend in every subgroup can reverse in the pooled data when group sizes differ. Stratify or adjust by the lurking variable.'],
    ['Testing normality to choose a test', 'Shapiro–Wilk rejects for trivial deviations at large n and never at small n, which is backwards. Look at the plot; think about the mechanism.'],
    ['Correlation for agreement', 'Two methods with r = 0.98 can differ by 30%. Use Bland–Altman limits of agreement or an ICC for agreement.'],
    ['Error bars without a label', 'SD, SE and 95% CI look alike and differ by √n and ~2√n. Say which one, and n.'],
    ['Batch confounded with condition', 'If all controls were run on Monday and all treated on Tuesday, no model can separate treatment from batch. Randomize samples across batches.'],
    ['Winner’s curse', 'The first significant estimate of an effect, especially from a screen, is biased upward. Expect replication to shrink it.'],
    ['Garden of forking paths', 'Choosing the analysis after seeing the data (which outcome, which covariates, which subgroup) inflates false positives even without intent. Pre-register or disclose.'],
];

export const REPORTING = [
    ['Two-group mean', 'Mean (SD) in each group, difference with 95% CI, test, statistic with df, p, effect size.', 'Fasting glucose was 5.8 (SD 0.9) vs 5.3 (SD 0.8) mmol/L; difference 0.5 (95% CI 0.2 to 0.8), Welch t(96) = 3.2, p = 0.002, d = 0.6.'],
    ['Two proportions', 'n/N (%) per group, risk difference and ratio with CIs, test, p.', 'Response: 24/60 (40%) vs 12/60 (20%); difference 20 pp (95% CI 4 to 36), RR 2.0 (95% CI 1.1 to 3.6), χ²(1) = 5.7, p = 0.02.'],
    ['Regression', 'What was adjusted for, the coefficient on its natural scale with CI and p, model fit or n of events.', 'Adjusted for age, sex and smoking, each 1 kg/m² of BMI was associated with 8% higher odds of diabetes (OR 1.08, 95% CI 1.05 to 1.11, p < 0.001); n = 1,240 with 180 events.'],
    ['Survival', 'Median follow-up, medians per group, HR with CI, log-rank p, the curves.', 'Median follow-up 3.2 years. Median PFS 14.1 vs 9.8 months; HR 0.68 (95% CI 0.52 to 0.89), log-rank p = 0.005.'],
    ['Correlation', 'r with CI, n, p; the scatter plot.', 'Expression correlated with dose (Spearman ρ = 0.46, 95% CI 0.21 to 0.65, n = 58, p < 0.001).'],
    ['Nonparametric two-group', 'Median (IQR) per group, the shift or probability of superiority, test, p.', 'Median 11 (IQR 8 to 15) vs 8 (IQR 5 to 11); Hodges–Lehmann shift 3 (95% CI 1 to 5), Mann–Whitney p = 0.004.'],
    ['Omics screen', 'Method, thresholds, numbers at each stage, how multiplicity was handled.', '1,204 of 18,310 genes were differentially expressed (DESeq2, |log₂FC| > 1 and BH-adjusted p < 0.05); batch was included in the design.'],
    ['p-values', 'Exact to two significant figures (p = 0.034), p < 0.001 below that, never “p = 0.000” or “NS”.', 'p = 0.034; p = 0.21; p < 0.001.'],
];

export const ASSUMPTIONS = [
    ['Independence', 'Think about the design: repeated measures, clusters, time series, spatial neighbours. No test tells you this; the design does.', 'Mixed model, GEE, cluster-robust SEs, or aggregate to the independent unit.'],
    ['Normality (of residuals)', 'Q–Q plot of residuals, histogram. Matters least when n is large (CLT) and most for prediction intervals.', 'Transform (log for right skew), rank-based test, bootstrap CI, GLM with the right family.'],
    ['Equal variances', 'Residuals vs fitted plot; group SDs. Do not use Levene/Bartlett as a gatekeeper.', 'Welch’s t / ANOVA by default; robust (sandwich) SEs; model the variance (gls).'],
    ['Linearity', 'Partial residual plots; add a squared term or spline and see if it matters.', 'Splines (ns, rcs), polynomials, categorize only as a last resort.'],
    ['Proportional hazards', 'Schoenfeld residuals (cox.zph); log(−log S) curves parallel?', 'Stratify on the violating variable, time-varying coefficient, RMST, AFT model.'],
    ['Overdispersion (counts)', 'Residual deviance / df ≫ 1; dispersiontest.', 'Negative binomial, quasi-Poisson, zero-inflated model.'],
    ['Expected counts ≥ 5', 'Look at the expected table (chisq.test(...)$expected).', 'Fisher’s exact, exact multinomial, Monte-Carlo p.'],
    ['No multicollinearity', 'VIF > 5 to 10; unstable coefficients with huge SEs.', 'Drop or combine predictors, regularize, accept wider CIs if the goal is adjustment not interpretation.'],
    ['Missing data mechanism', 'Compare those with and without missing values; think about why it is missing.', 'Multiple imputation (mice), full-information ML; complete-case only if MCAR or missingness is unrelated to the outcome.'],
];

export const DISTRIBUTIONS = {
    head: ['Distribution', 'Models', 'Parameters', 'Mean / variance', 'Shows up in'],
    rows: [
        ['Normal', 'sums of many small effects, measurement noise', 'μ, σ', 'μ, σ²', 'everything via the CLT; residuals in linear models'],
        ['Log-normal', 'products of many factors; concentrations, incomes, expression', 'μ, σ of log', 'e^(μ+σ²/2)', 'right-skewed positives; analyze on the log scale'],
        ['Binomial', 'successes in n trials', 'n, p', 'np, np(1−p)', 'proportions, logistic regression'],
        ['Poisson', 'counts of rare independent events', 'λ', 'λ, λ', 'rates, read counts (idealized)'],
        ['Negative binomial', 'counts with extra variability', 'μ, dispersion', 'μ, μ + μ²/θ', 'RNA-seq, events per patient'],
        ['Exponential', 'waiting time at a constant hazard', 'λ', '1/λ, 1/λ²', 'survival (simplest case); memoryless'],
        ['Weibull', 'waiting time with rising or falling hazard', 'shape, scale', '', 'parametric survival, failure times'],
        ['Gamma', 'positive, right-skewed; sums of exponentials', 'shape, rate', 'k/λ, k/λ²', 'costs, durations, GLM for skewed positives'],
        ['Beta', 'a proportion between 0 and 1', 'α, β', 'α/(α+β)', 'methylation β-values, priors on probabilities'],
        ['t', 'a mean divided by its estimated SE', 'df', '0, df/(df−2)', 't tests, CIs with small n; heavier tails than normal'],
        ['χ²', 'a sum of squared normals', 'df', 'df, 2df', 'contingency tables, likelihood-ratio tests, variances'],
        ['F', 'a ratio of two variances', 'df₁, df₂', '', 'ANOVA, comparing nested models'],
        ['Hypergeometric', 'draws without replacement', 'N, K, n', '', 'Fisher’s exact test, gene-set enrichment'],
    ],
};

export const GLOSSARY = [
    ['Absolute risk reduction (ARR)', 'The difference between two risks, in percentage points. The number patients actually experience.'],
    ['Adjusted p-value', 'A p-value corrected for how many tests were run, so it can be compared to α directly.'],
    ['AIC / BIC', 'Model comparison scores that penalize complexity; lower is better; differences under ~2 are noise.'],
    ['Allele frequency', 'The share of all chromosomes in a population carrying that allele.'],
    ['AUC', 'Area under the ROC curve: the probability that a random case scores higher than a random control. 0.5 is useless, 1 is perfect.'],
    ['Bayes factor', 'How much more likely the data are under one hypothesis than another. Evidence, not a posterior.'],
    ['Bootstrap', 'Resample the data with replacement many times to see how an estimate wobbles. Gives CIs when no formula exists.'],
    ['Censoring', 'The event has not happened yet when observation stops. Survival methods use the information that it had not happened by then.'],
    ['Confounder', 'A variable that causes both the exposure and the outcome, creating a spurious association. Adjust for it, or randomize.'],
    ['Credible interval', 'The Bayesian interval: a 95% probability the parameter lies inside, given the data and the prior.'],
    ['Degrees of freedom', 'How many values are free to vary once the estimates are fixed; roughly n minus the number of parameters.'],
    ['Effect size', 'How big the difference or association is, in meaningful units. The thing a p-value is not.'],
    ['Exposure', 'The variable whose effect you want: treatment, genotype, environment.'],
    ['FDR', 'False discovery rate: the expected share of false positives among the results called significant.'],
    ['FWER', 'Family-wise error rate: the probability of at least one false positive across all tests.'],
    ['Fixed vs random effects', 'Fixed: the levels you care about (treatment). Random: a sample of levels from a population (which mouse, which centre), modelled by their variance.'],
    ['Hazard', 'The instantaneous event rate among those still at risk.'],
    ['Heteroscedasticity', 'Residual spread that changes with the fitted value. Robust SEs or a transform fix it.'],
    ['Interaction', 'The effect of one variable depends on the level of another. The only way to show two effects differ.'],
    ['Intention to treat', 'Analyze everyone as randomized, whatever they actually did. Preserves what randomization bought you.'],
    ['Likelihood ratio (diagnostic)', 'How much a test result shifts the odds of disease. LR+ above 10 or LR− below 0.1 is a decisive test.'],
    ['Linkage disequilibrium', 'Alleles at nearby loci occurring together more than chance; why a GWAS hit is rarely the causal variant.'],
    ['Marginal vs conditional', 'Averaged over the population (GEE) vs for a given individual or cluster (mixed model). Different numbers for non-linear models.'],
    ['Multiplicity', 'Running many tests. Each extra test is another chance for a false positive.'],
    ['Non-inferiority', 'Showing the new thing is not worse than the old by more than a pre-set margin. The CI must exclude the margin.'],
    ['Odds', 'p/(1 − p). Odds of 3 means three to one: 75%.'],
    ['Offset', 'A term in a count model fixed at coefficient 1, usually log(exposure), so the model works in rates.'],
    ['Overdispersion', 'More variance than the model (usually Poisson) allows. The default state of biological counts.'],
    ['Polygenic risk score', 'A weighted sum of risk alleles. Predicts on average; weak for any one person.'],
    ['Posterior', 'What you believe after seeing the data: prior × likelihood, normalized.'],
    ['Power', 'The probability of detecting an effect of a given size if it exists.'],
    ['Prevalence vs incidence', 'Prevalence: the share who have it now. Incidence: the rate of new cases per time.'],
    ['Propensity score', 'The probability of exposure given covariates; used to balance groups in observational data.'],
    ['Random effect', 'See fixed vs random effects.'],
    ['Residual', 'Observed minus fitted. The model’s leftovers; plots of them show what the model missed.'],
    ['Robust standard error', 'A sandwich estimator that stays valid under heteroscedasticity or (with clustering) correlated observations.'],
    ['Shrinkage', 'Pulling noisy estimates toward a common value (empirical Bayes, ridge, DESeq2’s lfcShrink). Trades a little bias for much less variance.'],
    ['Standard error', 'The SD of an estimate across hypothetical repeats. SE of a mean = SD/√n.'],
    ['Standardized coefficient', 'The effect per SD of the predictor (and sometimes per SD of the outcome), making predictors comparable.'],
    ['Stratification', 'Analyzing within levels of a variable and combining, to remove its confounding.'],
    ['Type I / II error', 'Calling an effect that is not there (α) / missing one that is (β = 1 − power).'],
    ['Wald vs likelihood-ratio test', 'Wald uses β/SE; LRT compares model fits. LRT is more reliable with small samples or extreme estimates.'],
    ['Winsorizing', 'Capping extreme values at a percentile instead of deleting them.'],
    ['z-score', 'How many SDs a value is from the mean. Also the test statistic for normal-approximation tests.'],
];
